name: Compile snapshot with Maven

on:
  push:
    branches-ignore:
      - develop
      - master
      - xp
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
#    environment:
#      name: development
#      url: https://repo.andrei1058.dev
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '19.0.2+7'
          distribution: 'adopt'
      - name: Deploy snapshot with Maven
        run: |
          sudo apt install jq -y
          export UPDATE_VERSION=$(cat version.txt)
          mvn versions:set -DnewVersion=$UPDATE_VERSION-SNAPSHOT
          mvn versions:update-child-modules
          mvn clean install -s ci_settings.xml
          echo "UPDATE_VERSION=$UPDATE_VERSION" >> $GITHUB_ENV
